
define h = Character(_("Hiri"), colour="#f029c1")
define p = Character(_("player"), colour="#2f98f5")

define prof = Character(_("Lecturer"), Colour="#fcfafa")

define l = Character(_("Sasha"), Colour="#fcfafa")

image lecturer = "lecturer.png"

image Love alert = "alertLI.png"
image Love amused = "amusedLI.png"
image Love neutral = "neutralLI.png"

image badPaper = im.Scale("bad.png", 345, 460)

image cuteBg = "pamphlet/cute/pinkBg.png"
image cuteUni = "pamphlet/cute/University of Wartshog.png"
image cuteSign = "pamphlet/cute/welcomingSign.png"
image cuteImage = "pamphlet/cute/cuteRain.png"
image cuteInvite = "pamphlet/cute/inclusive.png"

image classyBg = "pamphlet/fancy/blueBg.png"
image classyUni = "pamphlet/fancy/University of Wartshog.png"
image classySign = "pamphlet/fancy/fancySign.png"
image classyImage = "pamphlet/fancy/rainbowClassy.png"
image classyInvite = "pamphlet/fancy/exclusive.png"

# The game starts here.

label start:

        scene bg lecturehall
        with fade
        show lecturer
        with dissolve

        prof"...so with all of that said, welcome to university. I hope that you will join societies soon."

        hide lecturer

        "You are greeted with a brightly coloured pamphlet decorated with drawings of rainbows."

        show badPaper at truecenter
        with move

        "Well, I am certain that this was made in MS Paint and that whatever design module this person has will not go over well."

        "I look up to see a beautiful girl. Must be the person who put this in front of me"

        hide badPaper

        show Love neutral
        with move

        l"Well, glad that's over. I did not catch your name, I am Sasha, I am running for the LGBT association club president."

        "Please enter a name for your character. Failure to do so will result in an autogenerated name being created"

        $ player_name = renpy.input("Hi, my name is...")

        $ player_name = player_name.strip() or "Blake"

        define p = Character(_("[player_name]"), colour="#2f98f5")

label m1:

menu:

    l"So, [p], would you vote for me, someone who would promote LGBT issues?"

    "Wow, so you designed this work of art? What an eye-catching pamphlet!":

        jump designGood

    "Well, I was looking at the pamphlet and I don't think that it's convincing anyone.":

        jump designDiss

label designDiss:

    scene bg lecturehall
    show Love neutral
    with dissolve

    l "I like the honesty but don't remind me, I hate it too. I threw it together this morning."

    l "I am in need of a designer."

    jump designer

label designGood:

    scene bg lecturehall
    show Love amused

    l"Oh come on, you're not convincing anyone that this is good."
    l"We are in dire need of a designer."

    jump designer

label designer:
    scene bg lecturehall

    "A designer? This is my chance!"

    show Love amused

    p "What a coincidence, I study design."

menu:

    "I'd be happy to help in designing a new one for you!":

        jump designProcess

    "I will ask around class if someone is interested in helping you.":

        jump badEnding

label badEnding:
    scene bg lecturehall

    "A designer? I guess someone from my year will turn up to help."

    show Love amused

    l"Well, thank you for that."

    "And like that you lose contact with her..."
    return

label designProcess:
    "TUTORIAL: The following is a Mini-game where you are tasked with using your design skills to progress the plot."
    "TUTORIAL: Choose one of the options that you find suitable when they appear to design the pamphlet."
menu:

    "A pink background seems cute!":
        jump cuteBg

    "A blue background seems classy!":
        jump classyBg
label classyBg:
    show classyBg
    with dissolve
menu:

    "A cute and welcoming font for the uni.":
        jump cuteUni
    "A fancy and classy font for the uni.":
        jump classyUni
label cuteBg:
    show cuteBg
    with dissolve
menu:

    "A cute and welcoming font for the uni.":
        jump cuteUni
    "A fancy and classy font for the uni.":
        jump classyUni
label classyUni:
    show classyUni at top
    with dissolve
menu:

    "A cute and welcoming font for the society.":
        jump cuteSign
    "A fancy and classy font for the society.":
        jump classySign
label cuteUni:
    show cuteUni at top
    with dissolve
menu:

    "A cute and welcoming font for the society.":
        jump cuteSign
    "A fancy and classy font for the society.":
        jump classySign
label classySign:
    show classySign at truecenter
    with dissolve
menu:

    "Oh! A cute rainbow will communicate how friendly the society is!":
        jump cuteImage
    "Oh! A fancy rainbow will communicate how cool the society is!":
        jump classyImage
label cuteSign:
    show cuteSign at truecenter
    with dissolve
menu:

    "Oh! A cute rainbow will communicate how friendly the society is!":
        jump cuteImage
    "Oh! A fancy rainbow will communicate how cool the society is!":
        jump classyImage
label cuteImage:
    show cuteImage at truecenter
    with dissolve
menu:

    "Most importantly, the time and place with a headline should come after the person's attention has been grabbed! The headline should be inclusive and welcoming to all students!":
        jump inclusive
    "Most importantly, the time and place with a headline should come after the person's attention has been grabbed! The headline should be sleek and invite all LGBTQ+ identities!":
        jump exclusive
label classyImage:
    show classyImage at truecenter
    with dissolve
menu:

    "Most importantly, the time and place with a headline should come after the person's attention has been grabbed! The headline should be inclusive and welcoming to all students!":
        jump inclusive
    "Most importantly, the time and place with a headline should come after the person's attention has been grabbed! The headline should be sleek and invite all LGBTQ+ identities!":
        jump exclusive
label inclusive:
    show inclusive at center
    with dissolve
    p"Tada! This is what I came up with just now!"
    hide cuteBg
    hide cuteUni
    hide cuteSign
    hide cuteImage
    hide cuteInvite
    hide classyBg
    hide classyUni
    hide classySign
    hide classyImage
    hide classyInvite
    hide inclusive

    show Love amused
    with dissolve

    l"Oh wow, I don't know what to say!"
    l"This looks really professional, thank you so much!"
    p"No, thank you! This was great practice for my studies!"
    l"You're on board, I bet there's going to be plenty of things you'll help with."
    jump president

label exclusive:
    show exclusive at center
    with dissolve
    p"Tada! This is what I came up with just now!"
    hide cuteBg
    hide cuteUni
    hide cuteSign
    hide cuteImage
    hide cuteInvite
    hide classyBg
    hide classyUni
    hide classySign
    hide classyImage
    hide classyInvite
    hide exclusive

    show Love amused
    with dissolve

    l"Oh wow, I don't know what to say!"
    l"This looks really professional, thank you so much!"
    p"No, thank you! This was great practice for my studies!"
    l"You're on board, I bet there's going to be plenty of things you'll help with."
    jump president


label president:

    scene bg lecturehall
    show Love neutral

    l"So... now that you're onboard I'd assume you wanna know more about our cause?"
    p"Wait a minute...you're cause, isn't that a bit strong... I mean it's not like this is racism or even sexism"
    "Oh god did I just say that, I hope she knew what I meant... oh I've truly ruined it now"
    l"But it is similar, in fact it's the exact same thing"
    p"Oh no of course I didn't mean to offend you in anyway"
    "She must hate me now, why did you have to question her? you idiot"
    l"Look you don't have to be nervous... I understand that you didn't mean to offend or hurt me in anyway, besides I'm a grown up after all I can handle an opinion"
    "Whew"
    p"So... you mentioned the LGBT society, are there elections going on right now or something"
    l"It's actually LGBTQ+"
    p"..."
    l"That was a joke, a bad one I now realize... but yeah there's elections going on now, the last president graduated, therefore there's a vacanc-"
    p"what did they graduate with a degree in?"
    l"Astrophysics"
    l"There's not really much of a competition for the job, so to speak haha. To be honest I only really have one competitor, the current favourite Alexa Davids, who to their credit was vice president for two years"
    p"you think she'll win?"
    l"they"
    p"huh"
    l"Alexa Davids prefered pronoun is they"


menu:

    "Sorry I just can't deal with all of this... political correctness. I mean how can saying she be offensive?":
        jump rival
    "Sorry that was really inconsiderate of me to assume they're gender, I can only hope you'll accept my apology":
        jump friend


label rival:

    scene bg lecturehall
    show Love alert

    p"P...pol...political correctness, you think this is political correctness gone wrong or something? we are talking about a persons identity!"
    p"I'm not trying to offend anyone but... i'm not gonna change who I am to suit the needs of a stranger and there mental illness"
    l"Mental illness?"
    p"We'll what else would you call it? you are born one gender and decide to change it because you feel that you're trapped in the wrong body... listen I sympathize I really do, but you can't expect other people to treat YOU differently"
    l"You can't be serious? are you serious? please say no"
    p"You're talking this all wrong!"
    l"How else do you want me to take this?"
    p"Like a normal person?"
    l"What's that suppose to mean?"
    p"See this is why people don't give opinions, you get all defensive and act as if we have to be stupid or something to think the way we do"
    l"I don't think you're stupid, just misguided or maybe ignorant"
    p"How dare you insult me! I never once insulted you, you're out of li-"
    l"Did you ever stop to think that maybe... just maybe Alexia isn't the only transgendered person in the world"
    p"Hmm it's clear to me what must be done"
    l"Oh yeah, and that is?"
    p"I must run against you in the elections, to stop you from infecting the rest of the university with your political correctness"


    "From now on you and Sasha are battling for the presidency, who will win and what consequences that will have are up to YOU"

    "The full game will have many mini games where the player affects the story through interactive design as they build there campaign and make moral choices, all of which will be included in further chapters."

    "In the meanwhile please visit https://www.stonewall.org.uk/category/trans-1 and https://www.mermaidsuk.org.uk/  for more information on transgender issues and for help dealing with any issues relating to transgender"

    "You are not alone"


    return

    label friend:

        scene bg lecturehall
        show Love amused

        l"Of course I accept your apology, we're only human after all."
        p"Thanks, so I have to admit I'm not really clued up on transgender issues... would you mind telling me about them?"
        p"If that's okay"
        l"Sure I'd be glad to disuss these issues, well first up, I'd say is a lack of transgendered toilets"
        p"And why might that be an issue? I mean couldn't trans females just go to the female bathroom?"
        l"Well... it's not as simple as that I'm afraid, see a trans female would have to use a cis male bathroom due to that being their gender offically, and until they fully transition they can't use a female bathroom"
        p"That's really, really stupid, so there's really no trans specific bathrooms?"
        l"Well some... how do I say this... some more progressive universities have them... but not Wartshog"
        p"That's terrible!"
        l"It really is, and this is just one of the issues that trans people face"
        p"Oh my god, what else could they face?"
        l"Well as I mentioned earlier the correct pronoun is really important as it helps a trans person to feel more like the identity that they know they are, regardless of birth gender"
        p"I understand how to fix the toilet issue but how do you fix the pronoun issue?"
        l"Well first you need to find away to inform the lecturers, discreetly  and that will help with the students knowing"
        p"Couldn't the person just tell the lecturer?"
        l"They could and in many cases they do, but it's humiliating for a trans person to have to explain what gender they want to be addresed as, besides none of us want to bring up our... dead name and all that comes with it"
        p"Hmm it's clear to me what must be done"
        l"Oh yeah, and that is?"
        p"I help you run against Alexia Davids in the elections, to help you help all transgender students studying here, now and in the future"

        "From now on you and Sasha are battling together as a team to help Sasha to get the presidency, who will win and what consequences that will have are up to YOU"

        "The full game will have many mini games where the player affects the story through interactive design as they build there campaign and make moral choices, all of which will be included in further chapters."

        "In the meanwhile please visit https://www.stonewall.org.uk/category/trans-1 and https://www.mermaidsuk.org.uk/  for more information on transgender issues and for help dealing with any issues relating to transgender"

        "You are not alone"

        return
